apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Application-Cluster
  region: eu-north-1
  version: '1.26'

vpc:
  subnets:
    private:
     eu-north-1a: { id: subnet-0b2a2b111ae758a90 }
     eu-north-1b: { id: subnet-0794cf56da799d6bd }

nodeGroups:
  - name: Workers
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true