apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Rancher-Cluster
  region: eu-north-1
  version: '1.26'

vpc:
  subnets:
    private:
     eu-north-1a: { id: subnet-04c0e3415c1cc9ff0 }
     eu-north-1b: { id: subnet-0433f58d872af8ab9 }

nodeGroups:
  - name: Workers
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true